### ISSUE TITLE
FYI: It runs on Altair 8800 

### ISSUE THREAD

**Issue by TheFausap** [petermichaux/bootstrap-scheme#6]
Hello Peter,
just to inform you I managed to rewrite the source using K&R style.
It works... it's a little bit slower (with only 62KB of RAM available), and to compile/assemble/link the interpreter, with Aztec C compiler, it takes 10 mins.

**Comment by petermichaux** [comment]
Wow, Fausto! Very good work!!!

**Comment by TheFausap** [comment]
Sorry if I posted here as an issue, but it seems the posting comments on your web site is disabled.
